### ISSUE TITLE
Twitter function not working?

### ISSUE THREAD

**Issue by MattAppleton** [getgrav/grav-skeleton-ceevee-site#13]
Hi — there, having a look at this skeleton and noticed the twitter integration seems NOT to work on the demo. When I try activating this with my test build, I notice a Twitter ID pulled from a bonafide account seems to be **8** characters not **18** as in your example code...

Furthermore, I can't get the widget to work even with a 'real' id — I don't suppose it would be possible to see a working example of this Twitter widget on the skeleton?

many thanks...

**Comment by duceduc** [comment]
Same here. I created a widget using the search and pasted the 18 digit id, but I do not see any tweets on the site.

**Comment by duceduc** [comment]
I got the twitter integration working. The .js needs to be updated to the latest version(17.0.3). Grab the file labeled as [twitterFetcher_min.js](https://github.com/jasonmayes/Twitter-Post-Fetcher) using this [link](https://github.com/jasonmayes/Twitter-Post-Fetcher). Copy and paste the newer version into the 'twFetcher.html.twig'. Besure to enclose the code between <script> ...code </script>

The pior instructions to grab the widget id is outdated. All we need is our twitter username to pull the feeds. Replace the existing lines with these in the twFetcher.html.twig and paste them at the bottom above the '</script>'
```
var configProfile = {
  "profile": {{ site.twitter.profile }},
  "domId": '{{ site.twitter.domId }}',
  "maxTweets": {{ site.twitter.maxTweets }},
  "enableLinks": {{ site.twitter.enableLinks }},
  "showInteraction": {{ site.twitter.showInteraction }},
  "showImages": {{ site.twitter.showImages }},  
  "showUser": {{ site.twitter.showUser }},
  "showTime": {{ site.twitter.showTime }}
};

twitterFetcher.fetch(configProfile);
```
In the site.yaml, replace the twitter lines (found at the bottom) with these. Make sure you add your twitter username in the profile line. Adjust the settings to your likings.
```
twitter:
  profile: '{"screenName": ''yourTwitterUserName''}' # Your widget name
  domId: 'tw-widget1' # HTML ID used in code
  maxTweets: 2 # How many tweets to display
  enableLinks: 'true' # Enable links
  showInteraction: 'false' # Show interaction
  showImages: 'false'  # Show images
  showUser: 'false' # Show user name
  showTime: 'true'
```
 Reload the page, and your feed should work.
